#goes through string s and tests whether the first letter of t matches
#when it does, it should move to the next letter of both t and s
#if the letter does not match, it should proceed with s, but go back to the beginning of t



def motif_counter(s,t):
   t_len=len(t)
   s_len=len(s)
   motif=''
   positionlist=[]
   position=1
   next_letter=position
   for letter in s:
      start=next_letter
      position=next_letter
      for i in range(start,start+t_len):
         motif+=s[position-1]
         if position<s_len:
            position+=1
      if motif==t:
         positionlist.append(start)
      motif=''
      next_letter+=1
   return positionlist



s='ACGTGATACGTGATGTAACGTGATACGTGATGCACGTGATACGTGATTCACGTGATTACGTGATACACGTGATACGTGATACGTGATACGTGATACGTGATGACGTGATGGACGTGATACGTGATCGACTGCTAACGTGATAAACGTGATGTCATACGTGATACCCTGTAAGGCACGTGATACGTGATACGTGATCCACGTGATGAACGTGATGGACATGACGTGATCGGGACGTGATACGTGATACGTGATTACGTGATATCCACGTGATCACGTGATACGTGATCACGTGATACACGTGATGACGTGATAAACGTGATACGTGATCACGTGATCACGTGATACGTGATTACGTGATGAGACACGTGATAAACGTGATACGTGATTTACGTGATATATAACGTGATACGTGATACGTGATAACGTGATGGATACGTGATCCACGTGATACGTGATTACGTGATACGTGATTGATCCACGTGATATGGCCACGTGATTCACGTGATTCATACGCGCCGAAACGTGATACGTGATGACGTGATGGACGTGATGAACGTGATATACGTGATGACGTGATGGACGTGATCGTATACGTGATACGTGATACGTGATCGTACGTGATATCCACGTGATGTACGTGATTCTACGTGATTCTCTTTAACGTGATAGTTAGCACGTGATTACGTGATCACGTGATACGTGATTACGTGATCTACGTGATATAGATTTAACGTGATCACATGAGACGTGATGAACGTGATGTGCCAGACGTGATGACGTGATGTACGTGATTACGTGATGCCCTACGTGATGTGACGTGATATACGTGATCGACGTGATCGACGTGATACGTGATCGGTACGTGATACGTGATTTTACGTGATGACGTGATTACGTGATGACGTGATGACGTGATTTACGTGATTACGTGATGGAGCTACGTGATTACACGTGATGCACGTGAT'
t='ACGTGATAC'
new_list=str(motif_counter(s,t)).strip('[]')
new_list1=new_list.replace(',','')
print(new_list1)
