#def seq_count(s):
#    ACGT={'A':0,'C':0,'G':0,'T':0}
#    for seq_letter in s:
#           seqletter=seq_letter.upper()
#           ACGT[seqletter]+=1
#    return (ACGT)
#s=open("rosalind_dna.txt")
#seq=s.read().strip()
#print(seq)
#seqcount=seq_count(seq)
#print(nucleotide for nucleotide in seqcount)
#print(seqcount['A'],seqcount['T'],seqcount['G'],seqcount['C'])
#print(seqcount.values())
#print(seqcount.keys())
#for nucleotide in seqcount.keys():
#    print(seqcount[nucleotide])




s='CTGGCGTGCGCCAGATTATGTACCGGGCGCCGCTCTGCGCTACATACAGTGTCGAAGTCCCATATGCCGTGCTCGACGAGTGTGAGGTAGGAGAGATTACATGCCAGGGGTGTACAGGGATCGGGAGATGGAACCTTGCCCGGGGTGATAACATACGACGGCACCTCAGTGGACATGATGAACCACCGGTTGCGGGACTGGTACTCCTGGCCCACCCCCGAGAGCGCCTTCGAGGTACCTGGTCAGTGGTCGTCGGGGTTACATGTGGTACGTACACGCTAGCTGTCGTTTAACGACTCCGTGAAGACTGGTCTTTCCCGTGTATCCAGCATCTGCCTCTCTGATCGGTACGTAGCCAAGGGCGTGAAAAACCGAGAGCTTTTTACACCATCACCCACATTGTCAGCTACTGATCTTGTTGCCCATCATGTGGAGAGACCAGCTACCAAGGATTTCTCGCTTGGCTTTGCATAGAGGCAGAGGTACGAGGTTCGACACCGAGCGGCAATATCATAATCGCACAACATCGGCCTTAGATCTAAGGGATTACGAAATATCGGGAGGACTGTGTAAGCCGAAGTAACTGCGCCTCTCCCATAAACGTAGGACCTGGATCAAATGCTATTATAAGGGCCTCAAAATCAACGGGTGAAAACATTACCAGTCTCGTTCGCGGTTCCCGCTCAGTCCTTTCAAACGTACGAGACTAGCCCCCGTCGCTAAACATGAGACAGACGGGACCTCGTCTCGGAGCCCCACTACGTTTCATGTCAGTACTGACACAGTTAGGTCGTAAAACGGTAGAATAAGGCTGCGGCATTATTGTGGAATATTGACAATCGGGACTCC'
ACGT={'A':0,'C':0,'G':0,'T':0}
for seq_letter in s:
    ACGT[seq_letter]+=1
print(ACGT['A'],ACGT['C'],ACGT['G'],ACGT['T'])
