def aminoacid_codons():
#http://en.wikipedia.org/wiki/Genetic_code#RNA_codon_table
#http://www.cbs.dtu.dk/courses/27619/codon.html
#http://www.biochem.ucl.ac.uk/bsm/dbbrowser/c32/aacode.html
#http://www.biochem.ucl.ac.uk/bsm/dbbrowser/c32/aastruct.html
    aa={'UUU':'F','UUC':'F',\
        'UUA':'L','UUG':'L',\
        'UCU':'S','UCC':'S','UCA':'S','UCG':'S',\
        'UAU':'Y','UAC':'Y',\
        'UAA':'X','UAG':'X','UGA':'X',\
        'UGU':'C','UGC':'C',\
        'UGG':'W',\
        'CUU':'L','CUC':'L','CUA':'L','CUG':'L',\
        'CCU':'P','CCC':'P','CCA':'P','CCG':'P',\
        'CAU':'H','CAC':'H',\
        'CAA':'Q','CAG':'Q',\
        'CGU':'R','CGC':'R','CGA':'R','CGG':'R',\
        'AUU':'I','AUC':'I','AUA':'I',\
        'AUG':'M',\
        'ACU':'T','ACC':'T','ACA':'T','ACG':'T',\
        'AAU':'N','AAC':'N',\
        'AAA':'K','AAG':'K',\
        'AGU':'S','AGC':'S',\
        'AGA':'R','AGG':'R',\
        'GUU':'V','GUC':'V','GUA':'V','GUG':'V',\
        'GCU':'A','GCC':'A','GCA':'A','GCG':'A',\
        'GAU':'D','GAC':'D',\
        'GAA':'E','GAG':'E',\
        'GGU':'G','GGC':'G','GGA':'G','GGG':'G'}
    #I=Isoleucine
    #L=Leucine
    #V=Valine
    #F=Phenylalanine
    #M=Methionine=START
    #C=Cysteine
    #A=Alanine
    #G=Glycine
    #P=Proline
    #T=Threonine
    #S=Serine
    #Y=Tyrosine
    #W=Tryptophan
    #Q=Glutamine
    #N=Asparagine
    #H=Histidine
    #E=Glutamic acid
    #D=Aspartic acid
    #K=Lysine
    #R=Arginine
    #X=STOP
    return aa

def codon(RNA):
#http://bioweb.uwlax.edu/genweb/molecular/seq_anal/translation/translation.html
    codons=[]
    while RNA!='':
        codons.append(RNA[0:3])
        RNA=RNA[3:]
    #print(codons)
    return codons

#def ORF(codons):
#    RNA_ORF={}
#    Met='AUG'
#    STOP=['UAA','UAG','UGA']
#    for strand, codon in codons.items():
#        if Met in codon:
#            RNA_ORF[strand]=codon[codon.index(Met):]
#        for item in STOP:
#            if item in codon:
#                RNA_ORF[strand]=codon[:codon.index(item)]
#    print('These are the strands with open reading frames: ',RNA_ORF)
#    return RNA_ORF

def translation(aa, RNA_ORF):
    SLC=[]
    for codon in RNA_ORF:
        if aa[codon]!='X':
            SLC.append(aa[codon]) 
    protein=''.join(SLC)
    print(protein)
    return protein

#RNA='AUGCUAAGUAGUUGCGCAUUAGGCAUACUGCGGGAAGGUAUCACUUCAACGGUGUCCGCACCAGCUCGCAGACAAAUUUCUAAUUCCCUUGCUGCAGCGACCUUCGCUCGACACAAUGCAAGGGUGUCGGCAGCCAUUGGCUGCCCACGGUCACACGUCCAGCUUGAAUCGACGGCCGUUGGCUUAUGGAACUCUCAACGUAUCCCGCUGAGGGUUAGCGAAUCAGGCAGUCGAACGUUUAGCCAGAUUCCCCAGGACAGAUUUCCCGGACGUUGGAGUAAUGUGCCCCGCCUAAGGUCGUUGACCCUAACUUUUCAUGAAGAGCCCAACUAUUAUGGCCUGCAAGACUUGCGAAUGGGAGGAAUGCAAAUUCAAGAAACCGGUGUCGGCGAGCGCCCACAUGCUCGCUUAACUGAAGAUGGCGGAGGGCUGUUCAUCCGGUGGCAAAGCAGCAUUUCAGAAUCAAUGCUCGAGGCAAUGGUUGGUAUAUCCAUGGUUACGUGUGUUACCCGUUUAAAUUCCUUGAUGGAACGUUGGUGCCCUAAAGGGAGGUUAGUAGAUUAUCGUUACGCAGUCAGGCUAUGGACAGCCAAAUGCGCGCCGAACCGCCCGUGCUUCUUACCGGCAUGUUCACGCGCCGUGGCGCUUCCGAAUCUACGGGCUGCUAAUUUGAGCUCCAGUGAUUUGGACCGACUUACACGCUCCCAGCAUAGUGAACCGCGGCCGAUCGCUACCUUGCACCAUGUCUCCUCAAAGCCUAUUCUCCGGGCACGUCCUCGGUGGCCUAGGAGUUAUCUUCCUUCGGUAGGGCCGUAUUUAAGCAAGGUAUUACUUUGGCUCUUGAUCGCUCCCCGAAUCGUUAGCACAAAAAGUAGCUGCUACGACUCUCGACCUCGGCCGCCCACCUGCAACCCGGGGACUAGCUUACUUAAGACAUAUUUGUUAGUUCCAGCGCCAAGCACAGCGUAUGGAAAAACUUGCGGCUCUUCUGGGACUUCAGACUCGUGGAUCGCGUUUCUAACAACCAUCUCCCGCGAUCGGUACACCGCGCCUGCAGGCGAUCCAACACAAAUAUAUCGGAAUAUAAGUCCAGAGCGAAGUAUGGUGAUUCGGACACGGUCCGCAAAACGGACAAAUCGGGACGGAUGUUCGCGAUCCAGGAGGGAGUGUGUCAUCCACAACUUCGUCAAUGUGGCCAUCCGGUGUCUACGCCGCCUCCGAGCCGCCCAAGACGCCUUAUGUGCCGCCAUAUCGCGAAGUCCUUACCGUCGAAUUUCGGUCUCCGACGUGGUGGACGCGGGCAGAGAGAGUGCCUCCGUCUUAUUGUCUCGGUCACUGGUCUUUGUUUUUCGCAAGUAUCAGCACAGCACAGUCACCCGUCCUGUGUAUUAUAAAGGUCGUCUAGACUGUCGUGGCUUGUUUUUCUGCUUACACCGUACCACCCGACCUGCAGGGUCGGAUGCACUAGACGGACGGGGCUGUCCGCCUCAGCAGUCGCUGAAGGUCAGGGAUGGUUCCUUCCUGCCGCGUUUCAGAUGGAGUCCGAAUAGUACAAACCCGCGGACAUUGACAGAUGUUCGAACAAGAUACACCAGGAAGUGGUGUCAGGCCACCCGGUGUAAACCCUGGAAUAGGAUGCAUUGGCAGCGCUCGAGCGUUAAUCAGGGGGAUGGCAACUCUAUAAUCAGCAUCAGAGGCGGCGACCAUUACAGUAUCCCCUUAGGCACGUCAUCACGACGCAACAGCCACUUGCUAUGCGCAGCAACGGUAGCAAGUCGUAUCACAACAGCACCCUAUACUCAGCCCCAUAGGCCGUAUUAUCUCUACGACCCACCUAACCAAAAACUUCGUGGGCGAUACGAAAGGCAUUCAAGAAGGCCAAAGUGGCGAAGUGGUCCUUGUACAUCAGACUGCGGACGGAGUGUAGCUCCCCGACUCAUAACUGAGGCUUUCAAGCUUACAAAAGCCCACUCUGUGUGUGCAUUCCCCACCAUAACGAAACCACCUACACCGAGAUUGCCCCAGCAGCUACCCUCGAAACGUGUUCCGCCGGCGAGGAGGGAUUACUCCCGGGGUGUGUACCGUGUCCUAUCGCCUCUGCAGGCAGCUGGGGGGCGCAGCCCACCCUGGCCCGCUGAACGAUCCCGUUUAGUCGUCUUAGAUUGGGACACUCAUCGUCACCUACCCCACGAAGACAAUUAUGUUUACCAGAAAGCUCUUUUAGUAUCGUUAGGCGGUCUUGCGGGAGGUACCCGACUCUUCAACGGAAGAACGGUUCUGACGUGUGACCGCACCAAACAACAAAUUUUUUGCGACAUGCGCAUUGAGAAGCUGAGCUGCGUGAGGUCGGACUCAACACGCGCUUCAAAACUUUUCCGAGUCUCAAAGCAACGCAGGCCAAAUACUUGUGAGACUCGAUCAACGUGGCCCGCUCCGCAGGUUUACGGCCCAGCUGUAAUGAUGGUGCUCUUGGAUACUUCUGUUCAUAGGAGAUUAUUUCUCCGGGUAAAAUAUUGUGCCAGCGAUACGGUUAUUUUUAGCGUCUGCCAAUUCGUCAGGGACCAUCAAGACGGUCGGGUAUGCAACGAAACUACUACUAUACGGCCAAUGUGCUUGGUCCUUAUGCUGCAGCGAAGUCCGUGGCAAUUGACGAUUUAUUGCUUAAUUCAGAGAUACAGGCCGUCGUACCACCUGCCAGAUCACUGGUCACUUAGUGGCCCUCAAGUGGAUGGCCCGAUAUCACGAGACUGUCUGGUUAAAAUUGUGAUUACCCAAGGAAAGGUACGUGCUAGUCACACACGCUCGAAUCGACGAAAACCGGCUAGACACAUAAAUGUCCCCUAUGUGUCGCUCAGGCUCGACCCAGGUUUGCCUGCCGCCAUCGCAUCAUGUCUUAUAGCUACUGCUUAUCUAGCAGCCCCUCACGCGCUCCGGGAAGCAACUUUACCGCGUGAUGUAGGAAGAGAACCUCCCGACCUCAAACGUCCGCUCAGAUCCAUCCACGUGGGUUGUUCUCUACCUGAAAUGUUAUACGGGGGAAAUCGAGGCGAAGCGCGUCUUGACUUUGAGCAAUGCGAAGGGCAGAGCCAAUGUGAAACCCUGUUACGACCCAAUUCUAUCCGGUGCCGAAAGCCCGGCACAGCCCACAGCACGGGCGUGAUAGCACAGCCAUCCACUGCCUUAAACUCGAUGCGUAUGACCUUGGGCGAUAGACGGAGCUGUCUAGACUCGACAGCGCGCGCUUGCCCCACCGUGCAUCGUACUCGGGCAUUGUUCAGGAAGGCGUUGGCCCAUACAACUAUGCAGGUUGUGCUAUGGUUCUUAGUGUUCGGAGGUUGCCUCACCUGCGGUAACAAGCAUUGUAAGCUCUACCUACUCAUCUCUUGCCCUUUUUCUCACAUCCGGGAGGGGUUAACGGUUGUGCGCAAGGAUAUCGCUGCUAGUGCGGCCUAUUCGCUGUCCCGCUGUGGAGCAGUGGCGCCUGAUGGGCCCAAACUCCUACAACGAGAUCCCGUAGUCUCAAGCAAGUAUGUGGUCUCGAGUAGGAGUAGUGAGAUAAACAGACGCGGAGCGCGAUCCAGAUGUCAGUUAGGGACCACCGAUCGUCAACCCAUCAAAAGCGACCCGCAUGGAACUCCGAACUCUUUAGGAACAGGCGUUAAAUGUUUCAUACCGAGUAUAGACCGCAGGCAUCACGCAACCAUAAUCUUAGUACAUUUGCUACCGGAUUGUCACUUAGAGACAGCUAGGUUCUUUUCCGGCGAGCAAAGGAUACUUUGCCCUUGGAUUUAUGGCAUGAAUACUUUACAAACGACACUCUCUCUCGGCAUUCUGUUACGAGAGUACAGUCUAUCACUUUGCACGAUCCCCGAUAUACUUGAUCUCGCUACGUGGUAUCCUUGUUUAUUUGUCGAUUCGGAUGUACUGGCGCUCGUCCUUUCCUUCGGAUCCGGGUACGACUAUCGGUACCGCUUGGUUUUCCGUGAGACCCGCAUCAGUAUUGAAUCUUGCCCGUCCGGCAAAUUCUAUCAAAAAUGUCUCGUUUUCCGAGAACGGGCCGGCCCAAAGCUUGGGUCGUACGUUGCGAUCGACUGGUCGAUCUACUGGCUGAACUUGUUAGGACUGGGAGGAUCAGUACCCCGGGCCAAUAUGAUCUUUGUGCGGAACCUUAGCGUGCCAUCCCGGAUGCGAGAACCAGUUAGCGGAACGCAAGGUAGUCAGGAGCUACUCUGCAAAAUUAGCCCGCGUAUGAGGACGUACCUGCGGCUACCACGCGGAGCUCCCGGUGCCGUCUCCGGCUACGAGGCUUGUAUCUCCGUGCCUGAAUCCGUGACCCUGUGUGCGGAAGGAGCAUUCGUUGUGAAGCUGACUUAUGAGCCUAAGUACGUCCCCUAUAUACAUUUGUGUAUACCUUGCUUCCGCCUGCGAGGUCAAAGUGUUGCCGCCAGAAUGCCCGUUGCCCUCUCUGUCGUACAGGAUUCACGCAUUAGAUAUAAAACUUACGUACUGAAGGACUCGUUGUUCUUCCAGCCGCGGACUCCUUUACGGUUAAACCCUAGCUCUAAACUUAUACUGAACCCUAAAGUAAAGCCCUGCGACACGUAUGGAAGGGCCCAUCGGCGAACAGCUGGGGGUGCCACUCUGCGAACUUUAAUUCAAGGGCCAGAAAGACGGGCGUACGCUACAGUGUUUGUACACCUUUUCUGGAAGAUAUGUGGCUCGCACGAUAUGGAACCGAAGCAACUUGCCACCAGGCUUUCAUCGCCAGCCUCGUACGAAGCCCGAGCAGGCUGUACACUUUCUGAUAAACGUUCACACAGACAAAGUAUCCUCCCUUGCAGUCAGUUACCGGGUCUUUGGAGCAAAAGCGACAAUUGCACAUUACAAAUGAAAGACUACCGUGAAGUUUCGUCGUUACCUCUGCUCGGGGAAUACACACGUAAAUUUGUGGCAAAGCAGAUGCGGACAUACCUGAAGUUGGGUGGCAUCUCUAAACGCUGGGGAGCUCUCCCAUAUUAUCACUCCAUUCGGAAUGUUGCAAGCAAACAAUUAUCACCAUACUCGCUGUGCGGUUCACCCAGCUACCCCAAUCCUUCUUUCACCAUUUUUGACCAAGACACUAGAUAUUCAGAGUCGUGUGAAACCGACGUUUCCGAUUGCCUAGUCUCUCUCCCCGAGGUAUUUCGCCGUUCUAUUUCUCGCAACCACCUGUCUUUAACUAGAGGAGAGUCAGCGCAAGAGACAGCAACUGCUACUCCGCCAUUCGAUCGUAAGCGAUCGGGUCAUGAUCUUUAUACUCACGAUUCGCACGAAAUGCGUGCCCUAGAGGAUAUUACGAUAUGGCGAAACUUACCCUAUAACAUAUUCGAGAGCCGCCAGUGUCCCCGUUUCCUGAAGGAGAGGUAUAUAGUAACUACACUUCAAACUCUAGGAGAAGAUAGACAUGGGAGUUGGUCAUCGCCGGCGUUGGGAAGGUACAGAUAUUCUAAUAAACUCUUAUCUGCUCAAGACAUAACAAACACGGUAGUGGGCGCCUCGCGGAUUGGUAAGCAGCCUGCGUACGAUGCUUACUCGGGCCAUGUGUGCGUUGACAGAAUCUGCAGCGCUCUGACUCCAUACAGGCAUGUGCCCAGUACUCAGAAUUCACGUACACCUCACAGAGUUGAGGGCAUUAUUAGCUUUGGCUUAUGUUUUCUAUCUCGGAAUCUUAAUGUAGCAGUGCACCCGGAUGAGGAAGACAGUAGGACCCUAGCCCUCAUAACAAAUACCUCGUUUCCCAUUGAUCUUGUUUCACCCAGUCUCCACGCCGAGGCGCCACACAACUUCCCGGCGGUACAUUCUCCACUGGGGAUGGAACAAGCCUCCAAUAGUAUCAUGGGCGAUACUUUAAAAGGCGACCAAAAAGCCUACAGAGGCGAGGGAUCUGUUCUGGCGAUCCCGGCGAAUUUACCUGACAUAAGAGGGCCUGUCCUAUGUACCUUAAAAUCACCCUGCCCUGCCCGGGAACUUGAUCGGAUGACAUCGAGCUCCUACCUGGUUGCUCCGCCCCACAAGCGAACACGCGGGAGCCGGUCUGGAGCUUAUAUCUGUAUGUGUGACUGCCACUUCCCUGCGAGUCCCUUCGUGAAACUAGCUUGUGUUCAGACCUCCACCGUACGAGAUGAGGUACCUACGACUCUGUGGAUCCGGGGCGACACUCAGUUGACAGAUACCAGUGGUUUAAAGAGUAGUGGAGAAGCGAUGCAUUCAGCUACUCAUCCUCAGCCAACGGAGUCUACCCAGGGGACAGUCGACGGACCAUAUCCUUCAACGCGACGCUCUAAACCAGGCCGAUUAAACCAGGUCGCCUAUCUGUGGCUCGGGGGUAUUAAACGAGUUUUAUCGUAUAAUAAAGCUUCCCAAUUCCACGGAGCGAAUGCGUCAAUUCCUAUGAUGGAGUAUAUAAGAUUGUUUUCUACGGAUGCCACAACAGUACGAUGCCCAUGUGCUCCACUACACCAUCAGUCAAUGGUAAACGUCGGUAAGGACGGGGACUCUCCCCUCUCCCGGGUCCCGAAUCACAUAAAACUGCUAUCUGGGAGGACAAUGCAGUGCUGCCCACAGUUACCCUUUAUAAAUCUAGAAUUUGAGAUCCGUACGCGGGAGAGCAGCUCAAUUUUGAACCAGGUCUUCCAGCGUACGGUUAUCUGGACCAGCCCAAAAGGGCUCGUUUGCAUGCCGAGUCCUAUACAUGGCGAUUUCCAGAAGUCGUCCGUUUUCGUUAAGCAUAUUUCUUGUACCUGUCCAGAUGUGCUCCCAGCCUGUAUCACAGGAACUCACUGGGUACAAAACGGAGAGAAGAAAGUAUCGUCCAGUGUCGUGCGUCUACCACAUCCGGCUCUGUUAUCGACAGCGAGGGCAUUUAUAUCAGUAGUGGAAAAAUAUCAGAAGAGCGGCAUCAACCCGCCGUGUUAUCGAGGGAUUUCGGACCCAGUAGCGGUGCCCUCAGCGCUACACUGCUACGAAUAUUCGGGUGGUGGAAGCCAAGCAACGUGUCCUCAUCCAUUUCGGAUACUAGAGUUAAGCGCUUUUUGUUGGCUUGCGCACAAGGGAACUCUACGUCCAGUUGUAUACGUCCUAUGCUAUGGUUGGUACGGUAUGAAUCUCCCAGUGUGUGGCGAGUCUAACACUCGCCGGUUGGAUGGUCGGGAGUCGACCAUGUUACCUCGAUGGGUAGAGUCUGCGUCAAACGUGCUGAUGCUCAGCCGCUGCGCUACAGUCGCCGUCUAUUUACGAUGCGUAAUAAAGCCGAUAAGCCUGCAUGUCAAGCUCCCGAGGUAUUCGAUUUCUCCGGUACCUGGCAACUAUACGCCUCUACAAUAUCGACCCAGCCUCACAGGUUCGUCCCCAUCCCAUGUUUUGAAGUCCAUCUCCUCCGAGCCACUCAUCAUUCUCCUAGCGCCCAUCAGAUUUUUAUCGUCCUAUUAUCCUGAUUCGGCAAUGGGGAAAGGGGAGCAUGAGAGAAGGCUACCUCACGUAACGGCGGGUACGUCAAAAGCAGGUUUAAAACAUGACGUGUUUCGAUGGCCAGUACGCCAUGGACCCCAUGACGAAUCGGGGACCUCCAGCAUAGACGGUCUGUCAAGACCACGCGAUACCUACGAGACUAUCGAUCCGGGCCGUAAGAUUUCCGAGACCGUGAGCUACGGAGCUUGGUAUUGUUAUGUUGUGGCCCGCCUCGAGGGGGGACCGUCGUUGCUACGGGAUGAAUUUAGAAGGGAAAAAAGCACACGGGCCCGCGGGCGCUCUUUUCUAUCCGUUACUAAUGAUGAGCUUAUAAUUUCGCCCAUCCUAGAAUGGAGUACCGUACGUGCGACAGGUUUGUGGGCCGAAGGGCGUCUCGACGCCCAGAUGGCUGCAGUGCCCAUCUCUGCUUUCGUGCACUUUUGCGCGCAAGGGGUAAAGCGCCCCCUCCUCGGGAACUCAAUGAUCCACGCCAUCGUAGAUAAGGACAGAUAUCAGCUUGGCUCGCAAAUUAAAGACCGUUAUAUGGACCCGCCAUCGACGGGAAUUCCUAGUCCCGCGCGGGUCUACCCUGCACCGGACCAUCACCAGUUUGUAGAGCGUACGGCGAUCUCUGACUGGGGCGCCCGGAGGAGCGUAACCACUGCCAGUCGAAGUUCUGAGACAAUUGGCCAAAGUCUCCAAUUCUUUAAUCAGACAUCAGCCCUCGGGCGACAUCCUAUGCUUAUGCGGAUGUUAUUCGGAACGACCACUUCUCUGUGUCAUUGUGUGUCCCUUAUAGGUUCUGCUGUCGAUAAGUCUAGAUAUUCGCCUAUGCGAUCGAUAGCGGCGACGGUUCGUCCAUUCAUCCGUCCUAGUGAGCAGACAUUCACUAGACCGUUCUCCUCACGUCAAUGCUGCACCGUCAGGCGGGGUAGGCGCUUGCUUCUUGUGCAGCUCCAAGAGGACUCUCCACCUAUUGGUAUCUUUAGGAGCUGUUCGCAAGCAAACGCUCCAAGAGCCCGCUUCGCUGUUCAUUACUGUGUGAUCCCACAGUCAGAUCGGAAAGGUAUAGACGAAGGUAUGUCGUUAACGCUCUGGAAUCCUCACUUGCCAAGCUAUAGCUCCCCGCGGUGUAGGGCUCCUGAUUUUUUUGGUAACGUAAGGAGACGCAUUUCUGUAGGGCCGGUCGAAAGGGUGGCCCUGCCCCAAGAUGUGGCCUCUCGUAAUGGAGUUAACGGAGAAAUGUUUACUUGUUGCUUGUUUGCGUGCGCCCACUAUGUAUCCCUUAGGGCUAUAAUAUGUCUUACGAAUUUGUAUGAUUGUAACCCAGGUAUGUUAUUACAACCUUAUCCUAUCGUGACCCCAUUACCGCCACAUAACAAUCCACAAAGCAUAAGAGCUUAUCGAUGGGUAUCAUGCGGGAAGCGACGACGGACACGUAGCUGCCAACCAAGAUAA'
f=open("rosalind_prot.txt")
RNA=f.read().strip()
#print(RNA)
RNA_ORF=codon(RNA)
translation(aminoacid_codons(),RNA_ORF)
